### PR TITLE
Fix marker_header bug and update Dependencies

### PR DESCRIPTION
**Pull request by jonnywilliamson**

### CODE REVIEW

**Comment by jonnywilliamson** [comment]
Also in your travis build script it doesn't fire phpspec. Not sure if that's on purpose or not, but the phpspec tests where flagging the marker_header bug.

**Comment by jonnywilliamson** [comment]
Oh and a FYI I think symfony 2.8 is the latest LTS version if thats the reason 2.7 is in the composer.json file.

http://symfony.com/doc/current/contributing/community/releases.html

**Comment by ikwattro** [comment]
Thanks for the PR. I don't think I had any reason for 2.7 being there, surely it was the current version when I created the library.

**Comment by ikwattro** [comment]
@jonnywilliamson Tagged 1.4.0 with your PR inside

**Pull request merged**
